{"uuid": "febf065a-d059-4cec-a7de-b7da8cd80664", "children": ["1b146dfb-7fa2-4878-9753-2e98b396ba51", "c4e19d62-9b02-4c20-9878-d14e81109c5f", "7873daa8-17fd-48ff-9d32-90223d57ad63", "4bd29b8c-96a7-4522-9968-61b7b1cc4364", "87ac4b9a-8a2e-4305-99c3-fc6bbb4e05ae", "e913bd53-da16-4c63-a746-f5a67ea96977", "10a8a581-92e7-4682-97f1-ff25b841e5f0", "ba828e65-6365-4654-a8ad-5151c8d59d27", "9a3067b4-997f-45dc-a30b-d5831bcd875b", "167df83f-515f-4a88-9955-0bdcef99e367", "f3e5cb4c-6b6f-44cc-a28a-601dcd9ff097", "c366f1ef-1e45-4191-8903-0d1d82ea31fe", "7515b408-6fa5-4820-aab0-495f41cc906e", "d90c8905-ee9a-4d99-b28e-17a7832be9f0", "0c67c0d2-7c53-4d80-920e-7c7d86ff0813", "ed3d9d4a-223b-4ea2-8e5e-e781758f5693", "56f008ea-fc48-4f62-95e3-dff67704e8df", "1c82ba28-3eef-4b0b-9da9-4d10b759267a", "cc1bbd17-cba6-432f-8bfe-7625b7b7c76d", "541d1198-c6c5-4968-816d-443006975f70", "c58ac0f7-ab5c-4646-8063-2501c8dc8db0", "deec391c-30c0-4eaf-82c6-94fdd7bdeab2", "d13b4418-da9c-43b1-bda4-851270da63d7", "8f5ba24c-68e2-4c18-adec-7bf8f2d2ce5c", "665b5b85-d33a-47fc-a1ed-c75b60d4c3cb", "9793ff69-88ff-4ebf-a339-be6bc78df2db", "9aadbfcd-cd5f-4471-b9b6-c286d330e18d", "cdacb494-00c1-4ac9-8b72-6fb2272f781c", "c489cdfd-3c68-4727-a4d4-189dd1310ff8", "4d8dc3dc-fc9d-4ce2-ae43-a29544043832", "8513f985-1e54-42e3-b6e7-cc466b712731", "7243c8e2-be6b-4dea-b16a-fd4af09ac2ba", "ba67376e-42f1-4f97-b5e4-7399ae69293f", "313e5ce7-a3e2-4b0b-bbeb-fd94ee25dd11", "2454fc61-5711-4752-ae6e-03dcd01f14ec", "900e5368-4c64-46fd-9572-e594f06270c7", "8c151c04-45d2-4f5a-906d-ebbdede9ee11", "7073a882-f606-4827-9dc1-01acc39a1887", "5522ed5c-efaf-4ecf-87dd-9cb60fe252e4", "8c7638bc-5f79-4412-9b62-28594b60fad0"], "befores": [{"name": "_xunit_setup_class_fixture_Test_chamet", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001967295A050>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))\n", "trace": "  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 864, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 785, in _call_with_optional_argument\n    func(arg)\n  File \"C:\\Users\\pgk bqt\\PycharmProjects\\Chamet_project\\common\\party_Start_audiencecontinuous.py\", line 10, in setup_class\n    self.driver=appium_desired()\n                ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pgk bqt\\PycharmProjects\\Chamet_project\\common\\desired_caps.py\", line 34, in appium_desired\n    driver = webdriver.Remote('http://localhost' + \":\" + str(data['port']) + '/wd/hub', desired_caps)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 234, in __init__\n    super().__init__(\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 324, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1686800960383, "stop": 1686800976759}], "start": 1686800960383, "stop": 1686800984182}