{"uuid": "65b9fc69-158c-4d69-bc61-42d59c0dedb1", "children": ["d416d430-5c79-4b03-b9d9-707f8f969b6e", "1a796d15-d0f0-457e-9e3f-1d49145736dd", "4cab0fef-3379-4d0e-8480-c01c6a717cc3", "654b4cbe-71d7-4d5d-8080-3a1f6dacbe85", "8e44007d-a2da-4f04-83b0-d2765863b13a", "f3d7458a-3d64-4ced-b04d-b7084145dc1f", "4d824d19-33f5-4526-98f0-b9e1a840c33e", "024522d1-91a5-49fc-b042-cf585bd2db25", "00717568-7b5a-46ae-8372-7fc1b0640379", "2e867f0a-c1f4-4e14-b929-f0c0c7aa1846", "07f29d25-e2e8-4698-9b62-89c708600f39", "e69c057e-41e8-41ae-82ec-dff9d0c242ce", "5e785d1f-7257-4501-affb-3b92d2e00ade", "859a5590-498f-44ee-91b5-ac0a99dc88c8", "de9a905b-2ae5-46cc-8a26-182cdede5de0", "d51f3e1e-51ef-4c54-b92e-9b505d97fa09", "736d648e-dd64-463f-8730-cb247c9e214e", "b856ec10-e7a2-4824-9f71-47dbb9e6445e", "12f19294-51de-4160-bc78-8c94bfd63694", "d524b7cf-2bfb-43ee-bf91-9d9532593676", "6efeea3b-78d1-4694-a565-af6fdae2831b", "33d995ed-e7f3-4c5c-aaf0-01ce437764fe", "f5510491-bd75-4110-ad14-ee4b77ceca8d", "a32c1357-94fc-4e8d-b679-22a851eaed68", "48895717-9bbd-4399-84f3-d2752d610580", "c8bf7042-7de3-4159-a196-383677626b99", "01d7f8bf-1b05-4fa3-9dbc-6d0c6ff67449"], "befores": [{"name": "_xunit_setup_class_fixture_Test_chamet", "status": "passed", "start": 1686800581176, "stop": 1686800613190}], "afters": [{"name": "_xunit_setup_class_fixture_Test_chamet::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session/a4033ef3-8c49-4c21-825c-79430004bae0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002034E122390>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))\n", "trace": "  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 868, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 785, in _call_with_optional_argument\n    func(arg)\n  File \"C:\\Users\\pgk bqt\\PycharmProjects\\Chamet_project\\common\\party_Start_audiencecontinuous.py\", line 20, in teardown_class\n    self.driver.quit()\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 562, in quit\n    self.execute(Command.QUIT)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\request.py\", line 74, in request\n    return self.request_encode_url(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1686800884679, "stop": 1686800901040}], "start": 1686800581176, "stop": 1686800901040}