{"name": "用例60：主播端检查观众是否未上麦", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise", "trace": "self = <test_case.test_10party_mult.Test_multchamet object at 0x00000161F9A137D0>\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    @allure.title('用例60：主播端检查观众是否未上麦')\n    def test_TenParty_060(self):\n        logging.info('===用例60：主播端检查观众是否未上麦===')\n        try:\n            assert self.multanchor.second_guest()\n        except NoSuchElementException as e:\n            logging.info('===断言成功，观众未上麦===')\n            assert True\n        except:\n            logging.info('===执行失败===')\n            screen_name = self.multanchor.screenshot('party_ten')\n            logging.info(f'截图成功，图片为{screen_name}')\n            raise\n        else:\n            logging.info('===断言失败===')\n            screen_name = self.multanchor.screenshot('party_ten')\n            logging.info(f'截图成功，图片为{screen_name}')\n>           raise\nE           RuntimeError: No active exception to reraise\n\ntest_10party_mult.py:1328: RuntimeError"}, "attachments": [{"name": "party_ten", "source": "21eb95f4-0ee3-4b53-b687-0ae1744444e8-attachment.png", "type": "image/png"}, {"name": "log", "source": "7b2484b3-ec0c-471b-b7f4-b23623d5accf-attachment.txt", "type": "text/plain"}], "start": 1688377189118, "stop": 1688377193579, "uuid": "94286570-3666-467f-b942-244682d89d5b", "historyId": "5580de8fa0e4f7b1cb3585be994e6b03", "testCaseId": "5580de8fa0e4f7b1cb3585be994e6b03", "fullName": "test_10party_mult.Test_multchamet#test_TenParty_060", "labels": [{"name": "severity", "value": "blocker"}, {"name": "suite", "value": "test_10party_mult"}, {"name": "subSuite", "value": "Test_multchamet"}, {"name": "host", "value": "DESKTOP-8OL56K6"}, {"name": "thread", "value": "3444-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_10party_mult"}]}